#!/usr/bin/env python3
"""Finalize or check an econ-review v0.4 package as one fail-closed transaction."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
from safe_io import (  # noqa: E402
    atomic_write_bytes,
    atomic_write_json,
    atomic_write_text,
    canonical_portable_path,
    safe_read_bytes,
    sha256_bytes,
    strict_json_load,
)
from trust_spine import pdf_sources, validate_pdf_ingestions  # noqa: E402
from validate_review import validate_review  # noqa: E402


SCRIPT_DIR = Path(__file__).resolve().parent
GENERATORS = (
    SCRIPT_DIR / "generate_verification.py",
    SCRIPT_DIR / "generate_sources.py",
    SCRIPT_DIR / "generate_coverage.py",
    SCRIPT_DIR / "generate_reports.py",
    SCRIPT_DIR / "generate_fix_plan.py",
)


def load_object(path: Path) -> dict[str, Any]:
    value = strict_json_load(path)
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain an object")
    return value


def reject_symlinks(root: Path) -> None:
    if root.is_symlink() or not root.is_dir():
        raise ValueError("review directory must be a real directory")
    for directory, names, files in os.walk(root, followlinks=False):
        base = Path(directory)
        for name in names + files:
            path = base / name
            if path.is_symlink():
                raise ValueError(f"review packages may not contain symbolic links: {path.relative_to(root)}")


def run_generators(review_dir: Path, *, check: bool) -> None:
    run = load_object(review_dir / "run.json")
    for script in GENERATORS:
        if script.name == "generate_coverage.py" and run.get("mode") != "full":
            continue
        command = [sys.executable, str(script), str(review_dir)]
        if check:
            command.append("--check")
        result = subprocess.run(command, capture_output=True, text=True)
        if result.returncode:
            detail = result.stderr.strip() or result.stdout.strip()
            raise ValueError(f"{script.name} failed: {detail}")


def artifact_hashes(review_dir: Path) -> dict[str, str]:
    excluded_root = {"finalization.json", "review-actions.json"}
    artifacts: dict[str, str] = {}
    folded_paths: dict[str, str] = {}
    for path in sorted(review_dir.rglob("*")):
        if not path.is_file() or path.name == ".DS_Store":
            continue
        relative = canonical_portable_path(path.relative_to(review_dir).as_posix())
        if relative in excluded_root:
            continue
        folded = relative.casefold()
        if folded in folded_paths:
            raise ValueError(
                "review package contains case-ambiguous artifact paths: "
                f"{folded_paths[folded]}, {relative}"
            )
        folded_paths[folded] = relative
        artifacts[relative] = sha256_bytes(safe_read_bytes(review_dir, relative))
    return artifacts


def uses_current_generators(review_dir: Path, run: dict[str, Any]) -> bool:
    """Return whether the installed deterministic renderers created a receipt.

    Immutable v0.4 receipt-v0.1 packages and full receipt-v0.2 packages retain
    their original generated bytes. Their receipt hashes remain verifiable,
    but replaying a newer renderer would incorrectly demand a migration.
    """
    path = review_dir / "finalization.json"
    if not path.exists():
        return True
    try:
        value = load_object(path)
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError):
        return True
    version = value.get("schema_version")
    if version == "0.1":
        return False
    if version == "0.2" and run.get("mode") == "full":
        return False
    return True


def receipt(review_dir: Path, run: dict[str, Any]) -> dict[str, Any]:
    gates = [
        "source_integrity",
        "structured_verification",
        "report_generation",
        "fix_plan_generation",
        "contract_validation",
    ]
    if run.get("mode") == "full":
        gates[2:2] = ["structured_audit_v02", "burden_coverage_v02"]
    source_manifest = load_object(review_dir / "evidence" / "source-manifest.json")
    if pdf_sources(source_manifest):
        gates.insert(1, "source_ingestion")
    return {
        # Receipt v0.3 specifically certifies the full-review burden-coverage
        # guarantee. Quick reviews retain v0.2 because they do not carry that
        # artifact or gate.
        "schema_version": "0.3" if run.get("mode") == "full" else "0.2",
        "review_id": run["review_id"],
        "contract_version": "0.4",
        "artifacts": artifact_hashes(review_dir),
        "gates": gates,
    }


def readiness_errors(review_dir: Path, run: dict[str, Any], ledger: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    if run.get("schema_version") != "0.4" or ledger.get("schema_version") != "0.4":
        errors.append("finalization requires matching v0.4 run and findings contracts")
    if run.get("schema_version") == "0.4" and run.get("mode") == "full":
        required_component_versions = {
            "evidence/claims.json": "0.2",
            "evidence/analytical-audit.json": "0.2",
            "evidence/external-sources.json": "0.3",
            "evidence/coverage.json": "0.2",
            "evidence/writing.json": "0.4",
        }
        for relative, required_version in required_component_versions.items():
            try:
                component = load_object(review_dir / relative)
            except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
                errors.append(f"cannot validate {relative} contract: {exc}")
                continue
            if component.get("schema_version") != required_version:
                errors.append(
                    f"v0.4 full finalization requires {relative} schema_version {required_version}"
                )
        requested_addons = run.get("requested_addons")
        if not isinstance(requested_addons, list):
            errors.append(
                "v0.4 full finalization requires run.json.requested_addons (use [] when none were requested)"
            )
        try:
            figures = load_object(review_dir / "evidence/figures.json")
        except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
            errors.append(f"cannot validate evidence/figures.json contract: {exc}")
        else:
            if figures.get("figures") and figures.get("schema_version") != "0.2":
                errors.append(
                    "v0.4 full finalization with figures requires evidence/figures.json schema_version 0.2"
                )
        try:
            tables = load_object(review_dir / "evidence/tables.json")
        except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
            errors.append(f"cannot validate evidence/tables.json contract: {exc}")
        else:
            if tables.get("tables") and tables.get("schema_version") != "0.2":
                errors.append(
                    "v0.4 full finalization with tables requires evidence/tables.json schema_version 0.2"
                )
    if run.get("verification_passed") is not True:
        errors.append("run.json.verification_passed must be true before finalization")
    stages = run.get("stage_status", {})
    if not isinstance(stages, dict) or any(value not in {"passed", "bounded", "not_applicable"} for value in stages.values()):
        errors.append("all workflow stages must be passed, bounded, or not applicable")
    for finding in ledger.get("findings", []):
        if not isinstance(finding, dict) or finding.get("status") in {"dismissed", "resolved"}:
            continue
        if finding.get("severity") in {"critical", "major", "minor", "info"} and finding.get("verification") != "passed":
            errors.append(f"finding {finding.get('id')} has not passed verification")
    try:
        source_manifest = load_object(review_dir / "evidence" / "source-manifest.json")
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
        errors.append(f"cannot validate source ingestion readiness: {exc}")
    else:
        errors.extend(
            validate_pdf_ingestions(
                review_dir,
                source_manifest,
                run.get("review_id"),
                require_ready=True,
                require_canonical_paths=True,
            )
        )
    return errors


def check(review_dir: Path) -> list[str]:
    try:
        reject_symlinks(review_dir)
        run = load_object(review_dir / "run.json")
        if uses_current_generators(review_dir, run):
            run_generators(review_dir, check=True)
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
        return [str(exc)]
    return validate_review(review_dir)


def finalize(review_dir: Path) -> None:
    review_dir = review_dir.expanduser().absolute()
    reject_symlinks(review_dir)
    review_dir = review_dir.resolve(strict=True)
    run = load_object(review_dir / "run.json")
    ledger = load_object(review_dir / "findings.json")
    if errors := readiness_errors(review_dir, run, ledger):
        raise ValueError("; ".join(errors))
    with tempfile.TemporaryDirectory(prefix="econ-review-finalize-") as temporary:
        staged = Path(temporary) / "review"
        shutil.copytree(review_dir, staged)
        staged_run = load_object(staged / "run.json")
        staged_run["status"] = "complete"
        atomic_write_json(staged, "run.json", staged_run)
        finalization_path = staged / "finalization.json"
        if finalization_path.exists():
            finalization_path.unlink()
        run_generators(staged, check=False)
        run_generators(staged, check=True)
        atomic_write_json(staged, "finalization.json", receipt(staged, staged_run))
        errors = validate_review(staged)
        if errors:
            raise ValueError("staged package failed validation:\n- " + "\n- ".join(errors))

        # The receipt is the commit marker and is deliberately written last.
        commit_paths = [
            "run.json", "review-manifest.json", "README.md", "report.md", "fix-plan.md",
            "evidence/verification.md", "evidence/sources.md",
        ]
        if staged_run.get("mode") == "full":
            commit_paths.append("evidence/coverage.md")
        if (staged / "writing-report.md").exists():
            commit_paths.append("writing-report.md")
        rollback_paths = commit_paths + ["finalization.json"]
        previous = {
            relative: safe_read_bytes(review_dir, relative)
            for relative in rollback_paths
            if (review_dir / relative).exists()
        }
        try:
            for relative in commit_paths:
                atomic_write_text(review_dir, relative, (staged / relative).read_text(encoding="utf-8"))
            atomic_write_json(review_dir, "finalization.json", load_object(staged / "finalization.json"))
            errors = check(review_dir)
            if errors:
                raise ValueError("committed package failed final check:\n- " + "\n- ".join(errors))
        except Exception as exc:
            try:
                for relative in rollback_paths:
                    if relative in previous:
                        atomic_write_bytes(review_dir, relative, previous[relative])
                    else:
                        path = review_dir / relative
                        if path.exists() and not path.is_symlink():
                            path.unlink()
            except Exception as rollback_exc:
                raise ValueError(f"{exc}; rollback failed: {rollback_exc}") from rollback_exc
            raise


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("review_dir", type=Path)
    parser.add_argument("--check", action="store_true", help="Check an existing finalized package without writing")
    args = parser.parse_args()
    try:
        if args.check:
            errors = check(args.review_dir.expanduser().absolute())
            if errors:
                raise ValueError("\n- ".join(errors))
        else:
            finalize(args.review_dir)
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
        parser.exit(1, f"finalization failed: {exc}\n")
    print(f"econ-review finalization passed: {args.review_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
